export const STATUS_STR = {
  ACTIVE: 'Common_Label_ACTIVE',
  STOPPED: 'Common_Label_STOPPED',
  DELETING: 'Common_Label_DELETING',
  REBOOTING: 'Common_Label_REBOOTING',
  RESIZING: 'Common_Label_RESIZING',
  BUILDING: 'Common_Label_BUILDING',
  BLOCK_DEVICE_MAPPING: 'Common_Label_BLOCK_DEVICE_MAPPING',
  RESTORING: 'Common_Label_RESTORING',
  SUSPENDED: 'Common_Label_SUSPENDED',
  PAUSED: 'Common_Label_PAUSED',
  RESIZED: 'Common_Label_RESIZED',
  'IN-USE': 'Common_Label_IN_USE',
  DELETED: 'Common_Label_DELETED',
  AVAILABLE: 'Common_Label_AVAILABLE',
  ATTACHING: 'Common_Label_ATTACHING',
  DETACHING: 'Common_Label_DETACHING',
  'BACKING-UP': 'Common_Label_BACKING_UP',
  'RESTORING-BACKUP': 'Common_Label_RESTORING_BACKUP',
  NORMAL: 'Common_Label_NORMAL',
  SHORTAGE: 'Common_Label_SHORTAGE',
  WARNING: 'Common_Label_WARNING',
  ERROR: 'Common_Label_ERROR',
  FATAL: 'Common_Label_FATAL',
  INFO: 'Common_Label_INFO',
  CREATE_FAILED: 'Common_Label_CREATE_FAILED',
  CREATE_COMPLETE: 'Common_Label_CREATE_COMPLETE',
  UPDATE_IN_PROGRESS: 'Common_Label_UPDATE_IN_PROGRESS',
  UPDATE_FAILED: 'Common_Label_UPDATE_FAILED',
  UPDATE_COMPLETE: 'Common_Label_UPDATE_COMPLETE',
  DELETE_IN_PROGRESS: 'Common_Label_DELETE_IN_PROGRESS',
  DELETE_STOPPED: 'Common_Label_DELETE_STOPPED',
  DELETE_FAILED: 'Common_Label_DELETE_FAILED',
  DELETE_COMPLETE: 'Common_Label_DELETE_COMPLETE',
  CREATE_IN_PROGRESS: 'Common_Label_CREATE_IN_PROGRESS',
  DOWN: 'Common_Label_DOWN',
  PASS: 'Common_Label_PASS',
  NOPASS: 'Common_Label_NOPASS',
  FAILED: 'Common_Label_FAILED',
  ABORTED: 'Common_Label_ABORTED',
  INACTIVE: 'Common_Label_INACTIVE',
  CREATED: 'Common_Label_CREATED',
  PENDING_CREATE: 'Common_Label_PENDING_CREATE',
  PENDING_UPDATE: 'Common_Label_PENDING_UPDATE',
  CREATING: 'Common_Label_CREATING',
  'POWERING-OFF': 'Common_Label_POWERING_OFF',
  RESUMING: 'Common_Label_RESUMING',
  SHUTOFF: 'Common_Label_SHUTOFF',
  SHUTDOWN: 'Common_Label_SHUTDOWN',
  BUILD: 'Common_Label_BUILD',
  NETWORKING: 'Common_Label_NETWORKING',
  SPAWNING: 'Common_Label_SPAWNING',
  IMAGE_SNAPSHOTTING: 'Common_Label_IMAGE_SNAPSHOTTING',
  IMAGE_BACKINGUP: 'Common_Label_IMAGE_BACKINGUP',
  UPDATING_PASSWORD: 'Common_Label_UPDATING_PASSWORD',
  PAUSING: 'Common_Label_PAUSING',
  UNPAUSING: 'Common_Label_UNPAUSING',
  SUSPENDING: 'Common_Label_SUSPENDING',
  STOPPING: 'Common_Label_STOPPING',
  STARTING: 'Common_Label_STARTING',
  REBUILDING: 'Common_Label_REBUILDING',
  POWERING_ON: 'Common_Label_POWERING_ON2',
  POWERING_OFF: 'Common_Label_POWERING_OFF2',
  RESIZE_REVERTING: 'Common_Label_RESIZE_REVERTING',
  RESIZE_CONFIRMING: 'Common_Label_RESIZE_CONFIRMING',
  SCHEDULING: 'Common_Label_SCHEDULING',
  RUNNING: 'Common_Label_RUNNING',
  '': 'Common_Label_NULL',
  MIGRATING: 'Common_Label_MIGRATING',
  QUEUED: 'Common_Label_QUEUED',
  UPLOADING: 'Common_Label_UPLOADING',
  SAVING: 'Common_Label_SAVING',
  'POWERING-ON': 'Common_Label_POWERING_ON',
  DOWNLOADING: 'Common_Label_DOWNLOADING',
  ERROR_RESTORING: 'Common_Label_ERROR_RESTORING',
  REBUILD: 'Common_Label_REBUILD',
  APPENDING: 'Common_Label_APPENDING',
  REMOVING: 'Common_Label_REMOVING',
  POWERINGON: 'Common_Label_POWERING_ON2',
  POWERINGOFF: 'Common_Label_POWERING_OFF2',
  DISABLE: 'Common_Label_DISABLE',
  RESIZE_FINISH: 'Common_label_RESIZE_FINISH',
  RESIZE_PRER: 'Common_label_RESIZE_PRER',
  HARD_REBOOT: 'Common_label_HARD_REBOOT',
  REBOOT: 'Common_label_REBOOT',
  RESIZE: 'Common_label_RESIZE',
  ERROR_DELETING: 'Common_label_ERROR_DELETING',
  BACKING_UP: 'Common_label_BACKING_UP',
  RESTORING_BACKUP: 'Common_label_RESTORING_BACKUP',
  ERROR_BACKING_UP: 'Common_label_ERROR_BACKING_UP',
  ERROR_EXTENDING: 'Common_label_ERROR_EXTENDING',
  EXTENDING: 'Common_label_EXTENDING',
};

export const OPERATION_STR = {
  SUCCESSED: 'Common_OPERATION_Label_SUCCESSED',
  FAILED: 'Common_OPERATION_Label_FAILED',
};

export const STATUS_STR_IMAGE = {
  ACTIVE: 'Common_Label_IMAGE_ACTIVE',
};

export const STATUS_STR_WORKFLOW = {
  ACTIVE: 'Common_Label_WORKFLOW_ACTIVE',
};

export const NOTIFICATION_STATUS = ['info', 'warning', 'error', 'fatal'];

export const OPERATION_STATUS = ['Successed', 'Failed'];

